config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  
  get 'destination', to: 'quotes#destination'
  get 'about', to: 'quotes#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 280, minimum: 5 }
  validates :author, presence: true, length: { maximum: 50, minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order('RANDOM()').first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      if @quote.saying.length < 5
        flash[:error] = '<strong>Could not save.</strong> How you gonna inspire people to see the world with a quote that short?!'
      elsif @quote.saying.length > 280
        flash[:error] = '<strong>Could not save.</strong> Your quote is simply too long. You better make sure you didn\'t miss your flight typing it out!'
    elsif @quote.author.length < 5 || @quote.author.length > 50 
      flash[:error] = '<strong>Could not save.</strong> Don\'t forget to give credit where its due!'
      end
    end

    if @quote.saying[0] == '"' || @quote.saying[-1] == '"'
      @quote.saying = @quote.saying.tr('\"', "")
    end

    # UserMailer.confirm_or_no(@quote).deliver

    redirect_to root_path
  end
  
  def destination
  end

  def about
    @skip_footer = true
  end

  private
  
  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplurtyAbroad</title>
    <%= csrf_meta_tags %>
    
    <!--Favicon located in the app/public folder. Just change the name of the file to 'favicon' and rails will do the rest.-->
    <link rel="shortcut icon" type="image/png" href="/favicon.png" sizes="32x32" />

    <%= stylesheet_link_tag    "application", media: "all", "data-no-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "false" %>
    
  </head>
    
  <body>

    <div id="map-container">
    <div id="map"></div>

    <header class="row vcenter">
      <div class="col-3 col-sm-3">
        <%= link_to root_path, class: "logo" do %>
          <%= image_tag "plane_brad_woodard.png", class: "logo_image" %>
        <% end %>
      </div>
      
      <div class="col-5 col-sm-5 site_name">
        <span class="text">THE JOURNEY OF A THOUSAND MILES&nbsp;.&nbsp;.&nbsp;.<br /></span>
        <span class="hidden-xs-down slogan">Wisdom for those who dare to wander far and wide.</span>
      </div>
      
      <div class="col-4 offset-4 offset-sm-4 col-sm-4 text links">
        <%= link_to "Let\'s Go!", destination_path %><br />
        <!-- Button trigger modal -->
        <%= link_to "Add a Quote", "#", data: {toggle: "modal", target: "#myModal"} %><br />
        <!-- <%= link_to "Add a Quote", new_quote_path %><br>-->
        <%= link_to "About", about_path %>
      </div>
    </header>
    
    <!-- Modal -->

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Enter Your Favorite Travel Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "Add your quote here", placeholder: "The journey of a thousand miles begins with a single step." %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Lao Tzu" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Create", class: "btn btn-danger" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
    
    <div id="quote" class="container flex-grow">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-12 next-quote">
            <br /><%= link_to "Need more inspiration to get out and explore?", root_path, class: "next-quote" %>
          </div>
        </div>  
        
        <div class="row">
          <div class="col-12 col-sm-12 footer-blurb float-right">
            Proudly hacked somewhere along I-95 by <a href="http://justinholt.getforge.io/index.html" target="_blank">JVH</a><br />
            Build your own Splurty Web App! <a href="http://thefirehoseproject.com" target="_blank">Learn how to code here.</a><br />
          </div>
        </div>
      </div>
    </footer>
  
  <!--div for map-container -->
  </div>
  
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=GEOCODE_API&v=3&libraries=places&callback=initAutocomplete"></script>

  </body>
  
</html>

app/views/quotes/about.html.erb
<h1>About SplurtyAbroad</h1>
<div class="col-12">


  <div class="row">
    <div class="col-12 col-sm-4 vcenter">
      <%= image_tag 'JVH.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1 vcenter about glass">
      <div>
          <h5><p><span class="nobreak">SplurtyAbroad</span> was built by <a href="https://github.com/justinvholt/" target="_blank">Justin Velander Holt</a>, a storyteller, globetrotter and novice web developer who is striving to enhance his new skill set while living and working on the road. If you search the right location on this app, you might find him and his penguin mascot, Truxton, seeking out the best desserts in the region.</p> 

          <p>If you don't have a passport yet, he highly encourages you to apply for one <a href="https://travel.state.gov/content/passports/en/passports/apply.html" target="_blank" > here</a>.</p>

          <p>If you want to learn how to code, definitely consider <a href="http://www.thefirehoseproject.com/" target="_blank">The Firehose Project</a>.</p></h5>
          
      </div>
    </div>
  </div>
</div>

<br class="clear" />
<br />
<br />
<br />
<br />
<br />
<br />

app/views/quotes/destination.html.erb
<h1>Enter a city or country you'd like to visit</h1>
<input id="pac-input" class="controls" type="text" placeholder=" ">

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWe6kg7iXYs11CUtWN5nsk0lFIHy0KRd4&v=3&libraries=places&callback=initAutocomplete"></script>

app/views/quotes/index.html.erb
<h2>
  <span>SplurtyAbroad No. <%= @quote.id %>:</span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1>Enter Your Favorite Travel Quote</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>